### ISSUE TITLE
[Feature Request] Is there any plan for a plain vanilla boostrap 5 / js version of this project?

### ISSUE THREAD

**Issue by Frank-D** [creativetimofficial/vision-ui-dashboard-react#14]
### What is your enhancement?
Hi! Wow! This dashboard is absolutely stunnnnnning! I now almost regret not to have started my most recent webapp in react! 😆
My webapp is based on Svelte (SvelteKit actually.....instead of react/next.js for instance) and I'm using boostrap 5 for styling.

I was wondering if there's any future for me of using your completely amazing "Vision UI Dashboard", with my stack? (either a svelte version or plain vanilla bootstrap 5 version would do the trick)

Thanks, no matter your answer, wonderful work, really.
Cheers,
François

**Comment by simmmpleweb** [comment]
Hello, @Frank-D ! Thanks for using our products! We're happy to hear you enjoy our product! We are taking your idea into consideration, and we will announce you if this gets to production. 😁

Regards, Vlad.
