### ISSUE TITLE
[Bug] Google chrome performance issues

### ISSUE THREAD

**Issue by mutonby** [creativetimofficial/vision-ui-dashboard-react#3]
### Version
1.0.0
### Reproduction link
https://demos.creative-tim.com/vision-ui-dashboard-react/?ref=readme-vudreact#/dashboard
### Operating System
Mac and windows
### Device
Macbook pro and pc
### Browser & Version
Versión 100.0.4896.127 (Build oficial) (arm64)
### Steps to reproduce
Go to your demo preview: https://demos.creative-tim.com/vision-ui-dashboard-react/?ref=readme-vudreact#/dashboard with the latest version of google chrome
### What is expected?
Normal performance
### What is actually happening?
Lof performance

---

**Comment by simmmpleweb** [comment]
Hello, @mutonby ! Thanks for using our products! We need more details to help you with this problem. Regards, Vlad.

**Comment by mutonby** [comment]
Hello, Thx for your response.

Well the problem only is in google chrome last versión, all is working in the console I can't see errors, but the navigation is sow slow, I disabled all addons with mode incognito and nothing. With firefox and brave is working smooth. I sent  the url to other friends: https://demos.creative-tim.com/vision-ui-dashboard-react/?ref=readme-vudreact#/dashboard and all with google chrome not working well like me. Need some more details? Thx.

**Comment by centurions** [comment]
same problem

**Comment by mutonby** [comment]
some fix?

**Comment by simmmpleweb** [comment]
Hello! We tried optimizing the images. However, the real problem might be related to the gradients used all over the project, which are known to lower the performance. We hope we will come with a solution as quick as possible.

**Comment by mutonby** [comment]
Hello,

Why closed?

**Comment by simmmpleweb** [comment]
Hello! The gradients we used throughout the dashboard might slow your computer a little bit. However, the design of the dashboard is based on gradients, and it would not be a good decision design-wise to remove them.

**Comment by mutonby** [comment]
But why only slow in google chrome? and not in firefox and brave?
