### ISSUE TITLE
[Bug] Warning : Failed prop type: Invalid prop variant of value standard supplied to ForwardRef(_c)

### ISSUE THREAD

**Issue by Anonymous7code** [creativetimofficial/vision-ui-dashboard-react#6]
### Version
React v18
### Reproduction link
https://github.com/creativetimofficial/vision-ui-dashboard-react
### Operating System
Windows
### Device
Asus Vivobook 15
### Browser & Version
Brave@latest
### Steps to reproduce
npm start
### What is expected?
There should be no warnings in console
### What is actually happening?
Warning: Failed prop type: Invalid prop variant of value standard supplied to ForwardRef(_c), expected one of ["gradient","contained"].
at _c (http://localhost:3000/static/js/bundle.js:7456:5)
printWarning @ react-jsx-dev-runtime.development.js:97

---

**Comment by simmmpleweb** [comment]
Hello, @Anonymous7code ! Thanks for using our products! In the new archive we solved most console warnings. Regards, Vlad.
